name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run command '...'
        2. See error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: tpa-version
    attributes:
      label: TPA Version
      description: "Run `tpa --version` to get the version"
      placeholder: "e.g., 0.1.6"
    validations:
      required: true

  - type: input
    id: typescript-version
    attributes:
      label: TypeScript Version
      description: "Run `tsc --version` to get the version"
      placeholder: "e.g., 5.7.2"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: "Run `node --version` to get the version"
      placeholder: "e.g., 20.10.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: trace-file
    attributes:
      label: Trace File Info (if applicable)
      description: If the issue is related to trace file parsing, provide details about the trace file (size, how it was generated, etc.)
      placeholder: |
        - File size:
        - Generated with: tsc --generateTrace
        - TypeScript project size:

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or error logs here.
